version: "3.9"
services:
  api:
    image: pulsercoder/skypro_pkuzmin_app:$GITHUB_REF_NAME-$GITHUB_RUN_ID
    networks:
      - my-network
    ports:
      - 80:80
    depends_on:
      pg:
        condition: service_healthy
    volumes:
      - ./docker_config.py:/code/config.py
  pg:
    image: postgres:latest
    networks:
      - my-network
    environment:
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_DB: $DB_NAME
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 10s
      retries: 5
networks:
  my-network:
